name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build project
        run: cargo build --release

      - name: Prepare binary
        run: |
          mkdir dist
          cp target/release/pomodoro dist/pomodoro-linux-amd64
          # You can add more steps here to compress the binary if needed
          # tar -czvf pomodoro-linux-amd64.tar.gz -C dist pomodoro-linux-amd64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/pomodoro-linux-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
